<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'protsantapola');
define('_DB_USER_', 'protsantapola');
define('_DB_PASSWD_', 'prots4nt4p0l42k19');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'KqThwD9dZKUSryQTHpSXbFnZL0nIv9apasCoRh9QgNL9MAd6YpsgEnjE');
define('_COOKIE_IV_', 'dwgeNbc3');
define('_PS_CREATION_DATE_', '2015-01-03');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', '');
define('_RIJNDAEL_IV_', '');
